modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"
[[mods]] #mandatory
modId="cobblemonrider" #mandatory
version="${file.jarVersion}" #mandatory
displayName="cobblemonrider" #mandatory
authors="Zanckor" #optional
description='''
Makes possible to ride pokemons on cobblestone.
'''
[[dependencies.cobblemonrider]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[47,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.cobblemonrider]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.21)"
   ordering="NONE"
   side="BOTH"
